version: '3.7'

volumes:
  database_data: {}
  cache_data: {}
  webserver_data: {}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.1/16

services:
  database:
    image: library/postgres:12.3-alpine
    logging:
      driver: none
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    env_file:
      - ./backend/misc/docker/datastore/.database.env
    ports:
      - 25432:5432
    networks:
      - default

  cache:
    image: library/redis:6.0.3-alpine
    logging:
      driver: none
    volumes:
      - cache_data:/data:rw
    ports:
      - 26379:6379
    networks:
      - default

  backend:
    env_file:
      - backend/config/.env
    build:
      context: .
      dockerfile: ./backend/misc/docker/backend/Dockerfile
    depends_on:
      - database
      - cache
    volumes:
      - ./backend:/app
    ports:
      - 12095:12095
    networks:
      - default

  webserver:
    image: library/caddy:2-alpine
    depends_on:
      - backend
    volumes:
      - webserver_data:/data:rw
      - ./backend/misc/docker/webserver/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
